name: 'Codecov'
description: 'Github action that uploads coverage reports for this repository to codecov.io'
author: 'Ib @ Codecov'
inputs: 
  token:
    description: 'Set the repository token' 
branding:
  color: 'red' 
  icon: 'umbrella'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
