name: 'Codecov'
description: 'GitHub action that uploads coverage reports for your repository to codecov.io'
author: 'Ibrahim Ali @ Codecov'
inputs: 
  token:
    description: 'Set the repository token'
    required: false 
  file:
    description: 'Path to coverage file to upload'
    required: false
  flags:
    description: 'Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)'
    required: false
branding:
  color: 'red' 
  icon: 'umbrella'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.file }}
    - ${{ inputs.flags }}