name: 'Codecov Github Action'
description: 'Github action that uploads coverage reports for this repository to codecov.io'
author: 'Ib @ Codecov'
inputs: 
  conf:
    description: 'Used to specify the location of the .codecov.yml config file'
    default: 'codecov.yml'
  file:
    description: 'Path to the code coverage data file to upload'
    default: ''
  flags:
    description: 'Flag the upload to group coverage metrics (e.g. unittests | integration | ui,chrome)'
    default: ''
  token:
    description: 'Set the private repository token (defaults to secret CODECOV_TOKEN)'
    default: ${{ secrets.CODECOV_TOKEN }}
branding:
  color: 'red' 
  icon: 'umbrella'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
