name: 'Codecov'
description: 'GitHub action that uploads coverage reports for your repository to codecov.io'
author: 'Ib @ Codecov'
inputs: 
  token:
    description: 'Set the repository token'
    required: false 
  file:
    description: 'Path to coverage file'
    required: false
branding:
  color: 'red' 
  icon: 'umbrella'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.file }}
